### ISSUE TITLE
Does webcall support audio conferences?

### ISSUE THREAD

**Issue by d5ve** [mehrvarz/webcall#1]
Hi, thank you for webcall.

Is it possible to use webcall to have more than two participants in a call? I'm looking for a simple browser-based voice chat system.

Thanks.

**Comment by d5ve** [comment]
Thanks for your reply @mehrvarz I'll take a look at the link.

**Comment by mehrvarz** [comment]
If you need more than 2 (or 3) participant, you will likely need a central media router. And once a media router is part of it, you cannot make the simple claim, that all data is being delivered P2P. It really comes down to this.

**Comment by d5ve** [comment]
Cheers @mehrvarz

I understand that conferences are way out of scope for this project. Thanks for your feedback.

**Comment by mehrvarz** [comment]
Hi @d5ve, conferencing is not out of scope. Point is that adding a central media router can be an ambiguous choice. Like a Tesla that comes with a plugin diesel. Being pure P2P is the more important feature in this case. And you never know, maybe conferencing can be done without a media router and we just didn't figure it out yet.
