### ISSUE TITLE
How can I run this on Termux?

### ISSUE THREAD

**Issue by anedroid** [mehrvarz/webcall#12]
Termux use Golang 1.18, so as in issue #6 it cannot be built. Also, Termux use non-standard file locations, and some packages must be modified to make it working on Termux. Would Webcall work on this environment if I build it using Golang 1.17? Maybe there is some pre-build package of Webcall for aarch64 which I can use?

**Comment by mehrvarz** [comment]
WebCall server v2.0.9 can be build with Golang 1.18 after a small modification. All you need to do is add one line of code to httpLogin.go. Open httpLogin.go and go to line 331, or search for:
> calleeClient.hub.WsClientID = 0

then add the following right below (as new line 332):
> fmt.Printf("lenGlobalHubMap %d\n", lenGlobalHubMap)

End result should look like this (fifth line below was added):

>        wsClientMutex.Lock()
>        delete(wsClientMap, wsClientID)
>        wsClientMutex.Unlock()
>        calleeClient.hub.WsClientID = 0
>        fmt.Printf("lenGlobalHubMap %d\n", lenGlobalHubMap)

That's it. Store the modified file over the existing one and you should be able to "go build" using Go 1.18 with no issues. (Btw, WebCall server v2.0.9 and Go 1.18 were both released in the same week in March with almost no overlap.)

I don't know Termux but a quick search revealed that Termux makes it easy to install the newest version of Golang. Hope you get it to work now. May I ask why you want to run WebCall server on Android?
