### ISSUE TITLE
server user management: reset, recover, or change passwords?

### ISSUE THREAD

**Issue by axb21** [mehrvarz/webcall#13]
Hi,

I'm sorry if there is an obvious answer to this or if it has already been answered. I looked through the documentation and closed issues that I could find.

Does the webcall server support resetting, recovering, or changing user passwords? Or, is there some way to do this manually to the backing data store? The probability that I will forget or misplace a password approaches 1 as the amount of time I use webcall approaches infinity 😃

Thank you!

**Comment by mehrvarz** [comment]
Hi. Can you think of a secure method to implement this, without storing email addresses on the server?

**Comment by axb21** [comment]
Ugh I hadn't even thought of that. 

If the user is still connected, perhaps that can be used to verify that they are the one who originally registered the id (send something over the connection and have them verify what they received). If the connection is down but there's some kind of cookie stored that is used to authenticate the user, perhaps that can be leveraged.

If the connection is down and there is no such cookie, though, I don't see a way to do it without changing the registration flow.

**Comment by mehrvarz** [comment]
Letting users change their pw while they are still connected is easily doable. (But would allow someone with access to your device to change the pw, too.) Letting an operator reset a pw would be simple to implement. This would require the user to connect and enter a new password. Both methods do not yet exist. Let's think about it a little more.
