### ISSUE TITLE
Twitter handle error: errorauth

### ISSUE THREAD

**Issue by gnusupport** [mehrvarz/webcall#17]
I have followed you on Twitter https://twitter.com/WebCall and I get error:

`Twitter handle error: errorauth` 

in application.

**Comment by mehrvarz** [comment]
When you get a "Twitter handle error: errorauth" on the client, that should also leave a similar log entry on the server. But I can't find a failed attempt in the last 48 hours. However, there were a couple of successful new tw handles in this time frame.

Can you do it again and then tell me the exact time you tried (as in "35m ago" or hh:mm UTC/CET/eastcoast)? It would be helpful to see what the server thinks is happening.

**Comment by mehrvarz** [comment]
Twitter support has been retired
