### ISSUE TITLE
Website is down  :(

### ISSUE THREAD

**Issue by HeCorr** [mehrvarz/webcall#2]
https://timur.mobi/webcall

**Comment by mehrvarz** [comment]
There was no downtime. The issue may be caused by [fail2ban.](https://github.com/fail2ban/fail2ban) If you send me your ip address, or the first half of it like: 11.22.x.x, that could help me fix the issue. You can get your ip via https://ip.me

**Comment by HeCorr** [comment]
Oh that's weird because I haven't used the website in months..  I really don't know how my IP could have been banned.. I should have checked it from a different IP.

Here's mine:  `45.164.x.x`

**Comment by mehrvarz** [comment]
> Here's mine: `45.164.x.x`

Found such an entry in the blocklist and removed it. Issue may have been caused by a nearby addr. Sorry for the inconvenience.

**Comment by HeCorr** [comment]
No worries! It works now, thank you very much!

**Comment by nscomputing** [comment]
Trying to install Webcall server using instructions found on https://timur.mobi/webcall/install. It seems that my IP 150.101.x.x is blocked by your fail2ban. Could you please check the status of my IP in your blocklist. If found please remove it. Thank you very much.

**Comment by ArtCore13** [comment]
But I used downforeveryoneorjustme and there it shows it is down...
Would that be blocked too?
