### ISSUE TITLE
Backups function problem

### ISSUE THREAD

**Issue by NCHU611A** [mehrvarz/webcall#21]
Hi, 
I can't find a file like "webcall_(yyyy-mm-ddThh+mm:ss).tgz" in the path "(home)/\_backup/".
I followed the steps on the site and it still doesn't appear (I've had the server running for over 48 hours).

Below is the content of my **config.ini** file.

> hostname = (mydomain)
> httpsPort = 8068
> wssPort = 8443
> insecureSkipVerify = false
> logevents = attach
> thirtySecStats = true
> turnPort = 3739
> turnRealm = (mydomain)
> turnIP = (myIP)
> **backupScript = backupdb.sh**
> **backupPauseMinutes = 240**

Then the following is the content of my **backupdb.sh** file.

> export MYDATE=\`date --iso-8601=hours\`
> tar cfvz ~/\_backup/webcall_db/\_$MYDATE.tgz db/*

Then the following is what my terminal shows.

> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript sync db's (backupdb.sh)
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript exec (backupdb.sh)...
> \# callBackupScript backupdb.sh err=exit status 2 log=(db/rtccalls.db
> db/rtccontacts.db
> )stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript sync db's (backupdb.sh)
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript exec (backupdb.sh)...
> \# callBackupScript backupdb.sh err=exit status 2 log=(db/rtccalls.db
> db/rtccontacts.db
> db/rtchashedpw.db
> )stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript sync db's (backupdb.sh)
> stats 0/0/0 calls:0/0 0/0 go:81
> callBackupScript exec (backupdb.sh)...
> \# callBackupScript backupdb.sh err=exit status 2 log=(db/rtccalls.db
> )stats 0/0/0 calls:0/0 0/0 go:81
> 

BTW I have put config.ini and backupdb.sh in the webcall folder.

Thank you.

**Comment by mehrvarz** [comment]
> callBackupScript backupdb.sh err=exit status 2 log=(db/rtccalls.db

backupdb.sh does not seem to find your *.db files in the db/ subfolder. Are there any .db files in the db/ subfolder? Or are they in the main folder? (Depend on the value of your dbPath keyword. By default the files should land in the db/ subfolder.)

The proposed backupdb.sh script attempts to create archives in the ~/_backup/ folder. Note that this target folder needs to exist. Either create it once, or alternatively modify backupdb.sh to have the archives be created in some other location.

If WebCall server is running, let it invoke backupdb.sh exclusively (like you did). But if WebCall server is stopped you can manually invoke backupdb.sh from the command line in order to test what it is doing. Note: If you invoke backupdb.sh manually while WebCall is running, the generated snapshots may not be fully consistent.

**Comment by NCHU611A** [comment]
I have created a folder (**\_backup**) at the path ~/.
And I manually invoked backupdb.sh from the command line when WebCall server is stopped.
Then the following is what my terminal shows.

> lab6611@lab6611-B85-HD3-A:~/webcall$ **bash backupdb.sh** 
> tar: db/rtccalls.db: Cannot open: Permission denied
> tar: db/rtccontacts.db: Cannot open: Permission denied
> tar: db/rtchashedpw.db: Cannot open: Permission denied
> tar: db/rtcnotif.db: Cannot open: Permission denied
> tar: db/rtcsig.db: Cannot open: Permission denied
> tar: Exiting with failure status due to previous errors

I found it was a **permissions issue**.
Then I changed the contents of the backupdb.sh file and tried again.

> export MYDATE=\`date --iso-8601=hours\`
> **sudo** tar cfvz ~/\_backup/webcall_db\_$MYDATE.tgz db/*

Then the following is what my terminal shows.

> lab6611@lab6611-B85-HD3-A:~/webcall$ **bash backupdb.sh** 
> [sudo] password for lab6611: 
> db/rtccalls.db
> db/rtccontacts.db
> db/rtchashedpw.db
> db/rtcnotif.db
> db/rtcsig.db

It worked.

But still the **same problem** occurs when I execute the WebCall server.

> lab6611@lab6611-B85-HD3-A:~/webcall$ sudo ./webcall 
> [sudo] password for lab6611: 
> ----- webcall   startup -----
> config.ini str  hostname=(My Domain Name)
> config.ini int  httpPort=8067*
> config.ini int  httpsPort=8068
> config.ini int  wsPort=8071*
> config.ini int  wssPort=8443
> config.ini str  turnIP=(MyIP)
> config.ini int  turnPort=3739
> config.ini str  turnRealm=(My Domain Name)
> config.ini str  dbPath=(db/)*
> config.ini str  logevents=(attach)
> config.ini int  maxRingSecs=120*
> config.ini int  maxTalkSecsIfNoP2p=600*
> config.ini int  turnDebugLevel=3*
> config.ini str  backupScript=(backupdb.sh)
> config.ini int  backupPauseMinutes=1
> config.ini int  maxCallees=10000*
> config.ini bool thirtySecStats=true
> DbOpen db/rtcsig.db
> DbOpen db/rtccalls.db
> DbOpen db/rtcnotif.db
> DbOpen db/rtchashedpw.db
> DbOpen db/rtccontacts.db
> outboundIP MyIP
> 2022/11/01 16:56:17.791 [INF] Gopher[NB] start listen on: [":8071"]
> 2022/11/01 16:56:17.819 [INF] Gopher[NB] start listen on: [":8443"]
> httpServer using embeddedFS
> httpServer http listening on :8067
> httpServer https listening on :8068
> turn server listening on 'MyIP' port=3739
> awaiting SIGTERM for shutdown...
> stats 0/0/0 calls:2/24 0/0 go:81
> serveWss (76011766482) callee init 0 ws=23048817840 MyIP:33472 v=1.1.7F_106.0.5249.126
> stats 1/0/0 calls:2/24 0/0 go:82
> stats 1/0/0 calls:2/24 0/0 go:82
> stats 1/0/0 calls:2/24 1/0 go:82
> stats 1/0/0 calls:2/24 1/0 go:82
> callBackupScript sync db's (backupdb.sh)
> stats 1/0/0 calls:2/24 2/0 go:82
> callBackupScript exec (backupdb.sh)...
> **\# callBackupScript backupdb.sh err=exit status 2 log=(db/rtccalls.db**
> db/rtccontacts.db
> db/rtchashedpw.db
> )stats 1/0/0 calls:2/24 2/0 go:82
> stats 1/0/0 calls:2/24 3/0 go:82

Below are the details of my webcall/db folder.

> lab6611@lab6611-B85-HD3-A:~/webcall/db$ ls -l
> total 136
> -rw-r----- 1 root root 32768 11月  1 16:37 rtccalls.db
> -rw-r----- 1 root root 32768 11月  1 16:37 rtccontacts.db
> -rw-r----- 1 root root 65536 11月  1 16:37 rtchashedpw.db
> -rw-r----- 1 root root 32768 11月  1 16:37 rtcnotif.db
> -rw-r----- 1 root root 65536 11月  1 16:38 rtcsig.db


Then below are the details of my webcall folder.

> lab6611@lab6611-B85-HD3-A:~/webcall$ ls -l
> total 14632
> drwxrwxr-x 2 lab6611 lab6611     4096 10月 27 16:23 atombool
> -rw-r--r-- 1 root    root          85 11月  1 16:42 backupdb.sh
> -rw-r--r-- 1 root    root         258 11月  1 16:21 config.ini
> drwxrwxr-x 2 lab6611 lab6611     4096 10月 27 16:23 db
> -rw-rw-r-- 1 lab6611 lab6611     1609 10月 23 19:39 dbLayer.go
> -rw-rw-r-- 1 lab6611 lab6611     1252 10月 23 19:39 dbObjects.go
> -rwxr-xr-x 1 lab6611 lab6611      431 10月 23 19:39 gobuild
> -rw-rw-r-- 1 lab6611 lab6611      410 10月 23 19:39 go.mod
> -rw-rw-r-- 1 lab6611 lab6611    11228 10月 23 19:39 go.sum
> -rw-rw-r-- 1 lab6611 lab6611     2494 10月 23 19:39 httpActions.go
> -rw-rw-r-- 1 lab6611 lab6611    12903 10月 23 19:39 httpAdmin.go
> -rw-rw-r-- 1 lab6611 lab6611    21295 10月 23 19:39 httpLogin.go
> -rw-rw-r-- 1 lab6611 lab6611     8763 10月 23 19:39 httpMapping.go
> -rw-rw-r-- 1 lab6611 lab6611    31375 10月 23 19:39 httpNotifyCallee.go
> -rw-rw-r-- 1 lab6611 lab6611    15866 10月 23 19:39 httpOnline.go
> -rw-rw-r-- 1 lab6611 lab6611    32029 10月 23 19:39 httpServer.go
> -rw-rw-r-- 1 lab6611 lab6611    23656 10月 23 19:39 httpSettings.go
> -rwxr-xr-x 1 lab6611 lab6611      360 10月 23 19:39 init.sh
> drwxrwxr-x 2 lab6611 lab6611     4096 10月 27 16:23 iptools
> -rw-rw-r-- 1 lab6611 lab6611      763 10月 23 19:39 LICENSE
> -rw-rw-r-- 1 lab6611 lab6611    22321 10月 23 19:39 main.go
> -rw-rw-r-- 1 lab6611 lab6611     2262 10月 23 19:39 readConfig.go
> -rw-rw-r-- 1 lab6611 lab6611     3308 10月 23 19:39 README.md
> -rw-rw-r-- 1 lab6611 lab6611     5996 10月 23 19:39 runturn.go
> drwxrwxr-x 2 lab6611 lab6611     4096 10月 27 16:23 skv
> -rw-rw-r-- 1 lab6611 lab6611     8157 10月 23 19:39 skvLayer.go
> -rw-r--r-- 1 root    root          79 11月  1 16:40 stats.ini
> -rw-rw-r-- 1 lab6611 lab6611    24103 10月 23 19:39 timer.go
> -rw------- 1 root    root        1708 10月 19 15:27 tls.key
> -rw-r--r-- 1 root    root        5612 10月 19 15:27 tls.pem
> drwxrwxr-x 2 lab6611 lab6611     4096 10月 27 16:23 twitter
> -rwxr-xr-x 1 lab6611 lab6611       43 10月 23 19:39 wcadmin
> -rwxrwxr-x 1 lab6611 lab6611 14574644 10月 27 16:24 webcall
> drwxrwxr-x 5 lab6611 lab6611     4096 10月 27 16:23 webroot
> -rw-rw-r-- 1 lab6611 lab6611    63616 10月 23 19:39 wsClient.go
> -rw-rw-r-- 1 lab6611 lab6611    10596 10月 23 19:39 wsHub.go


Hope this information can be helpful.
Thank you.

**Comment by NCHU611A** [comment]
I finally changed the permissions of all files in the webcall folder using the following command.

`~/webcall$ sudo chmod 664 *.*`

Then it worked.
The WebCall server can be executed from the command line without 'sudo' in it.

Then the following is the message displayed by the "backups" function.

> 11月 03 15:13:23 callBackupScript sync db's (backupdb.sh)
> 11月 03 15:13:23 stats 0/0/0 calls:17/104 2/0 go:85
> 11月 03 15:13:23 callBackupScript exec (backupdb.sh)...
> 11月 03 15:13:23 callBackupScript backupdb.sh done log=(db/rtccalls.db
> 11月 03 15:13:23 db/rtccontacts.db
> 11月 03 15:13:23 db/rtchashedpw.db
> 11月 03 15:13:23 db/rtcnotif.db
> 11月 03 15:13:23 db/rtcsig.db
> 11月 03 15:13:23 )
> 

Does this mean success?
Thank you.

**Comment by NCHU611A** [comment]
Ok!
Thank you!
