### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by NCHU611A** [mehrvarz/webcall#23]
Hi,
When I set "Nickname" to "1" and call my friend, my friend's phone will show as "unkonw".
When I set "Nickname" from "1" to "2" and call my friend again, my friend's phone will show "1".
When I set "Nickname" from "2" to "3" and call my friend again, my friend's phone will show "2".

The "Nickname" displayed will be the "Nickname" of the previous call.
Thank you.

**Comment by mehrvarz** [comment]
Thank you for reporting. A fix (in caller.js) should now be live and will be part of the next server drop (v3.2.13).

**Comment by NCHU611A** [comment]
Thank you!
