### ISSUE TITLE
Multilanguage support for WebCall

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [mehrvarz/webcall#26]
How do I help with the translation of the application into Brazilian Portuguese?

**Comment by mehrvarz** [comment]
I wonder how the language selection should be done, ideally. Use the client system language? Or add a language selection inside the app (under settings)?

**Comment by brunoalbertopeixoto** [comment]
I believe the language should be automatically selected by the user's system. However, there could be an option to select other languages.

**Comment by mehrvarz** [comment]
Can you help me with Brazilian Portuguese (pt-BR)?

dialButton		"Call"
hangupButton	"Hang Up"
greetingMessage	"Greeting message (optional):"
connectingText	"Connecting..."
ringingText		"Ringing..."
hangingUpText	"Hanging up..."
msgbox			"(Your message)"
nicknameLabel	"Nickname:"
callstatsLabel	"Call stats"
fullscreenLabel	"Full screen"

This is for the caller app only. (Starting small.)

**Comment by mehrvarz** [comment]
As an example, here the translation into German (de-DE):

dialButton		"Anwählen"
hangupButton	"Auflegen"
greetingMessage	"Gruß-Nachricht (optional):"
connectingText	"Verbinde P2P..."
ringingText		"Klingeln..."
hangingUpText	"Auflegen..."
msgbox			"(Deine Nachricht)"
nicknameLabel	"Kurzname:"
callstatsLabel	"Anruf Daten"

**Comment by brunoalbertopeixoto** [comment]
dialButton "Chamar"
hangupButton "Desligar"
greetingMessage "Mensagem de saudação (opcional):"
connectingText "Conectando..."
ringingText "Tocando..."
hangingUpText "Desligando..."
msgbox "(Sua mensagem)"
nicknameLabel "Apelido:"
callstatsLabel "Estatísticas de chamada"
fullscreenLabel "Tela cheia"








> Can you help me with Brazilian Portuguese (pt-BR)?
> 
> dialButton "Call" hangupButton "Hang Up" greetingMessage "Greeting message (optional):" connectingText "Connecting..." ringingText "Ringing..." hangingUpText "Hanging up..." msgbox "(Your message)" nicknameLabel "Nickname:" callstatsLabel "Call stats" fullscreenLabel "Full screen"
> 
> This is for the caller app only. (Starting small.)

**Comment by mehrvarz** [comment]
> dialButton "Chamar" hangupButton "Desligar" greetingMessage "Mensagem de saudação (opcional):" connectingText "Conectando..." ringingText "Tocando..." hangingUpText "Desligando..." msgbox "(Sua mensagem)" nicknameLabel "Apelido:" callstatsLabel "Estatísticas de chamada" fullscreenLabel "Tela cheia"

Thank you. You should be able to see this change in the app now.
Also added two more strings:

notAvailable  "não Disponível"
digAnswMachine  "Você está prestes a chamar um atendedor de chamadas digital"

**Comment by mehrvarz** [comment]
@brunoalbertopeixoto I do need 10 more strings. Below are the Portuguese variants (as an example). Can you help me with the Brazilian Portuguese? (Note: 3 strings get a user name attached behind: tryingToFind, TryingToGet, sorryUnableToReach. And one gets a user name put in front: isCurrentlyNot)

tryingToFind				"A tentar encontrar o"
thisCanTakeSomeTime	"Isto pode levar algum tempo. Aguarde, por favor..."
isCurrentlyNot			"não está actualmente disponível."
canYouWaitSomeTime	"Pode esperar algum tempo enquanto tentamos estabelecer uma ligação?"
yesPleaseTry				"Sim, por favor tente"
noIHaveToGo			"Não, eu tenho de ir"
TryingToGet				"A tentar telefonar ao"
onThePhonePleaseWait	"Por favor, aguarde..."
sorryUnableToReach		"Incapaz de contactar o"
PleaseTryAgainALittle		"Por favor, tente novamente um pouco mais tarde."

**Comment by mehrvarz** [comment]
Some context...

![Screenshot-1](https://user-images.githubusercontent.com/205967/223478798-52776d2b-1cb5-403d-b6dd-81cf18e21cd8.png)
![Screenshot-2](https://user-images.githubusercontent.com/205967/223478854-90bb4a58-2996-402c-b123-ca73f29caced.png)
![Screenshot-3](https://user-images.githubusercontent.com/205967/223478905-ae1300d4-f7d9-49e5-8d74-dee93fc3d6b8.png)

In the 2nd image "this user" will be a name. The text "is currently not available" needs to be translated ('isCurrentlyNot'). Let me know if you have any questions.

A multimedia mailbox would be a very nice feature, no doubt. It would also blow up the storage requirements (currently close to zero).

**Comment by brunoalbertopeixoto** [comment]
tryToFind "Tentando encontrar (this user name)"
thisCanTakeSomeTime "Isto pode levar algum tempo. Aguarde, por favor..."
isCurrentlyNot "(this user name) não está disponível no momento."
canYouWaitSomeTime "Pode esperar algum tempo enquanto tentamos estabelecer uma ligação?" (I found this text too long.  "Você deseja esperar enquanto tentamos estabelecer uma conexão?
yesPleaseTry "Sim, por favor tente" (I found this text too long.  I would put, even in English, "Sim"/Yes)
noIHaveToGo I found this text too long.  I would put, even in English, "Não"/No)"
TryingToGet "Tentado ligar para (this user name)"
onThePhonePleaseWait "Por favor, aguarde..."
desculpeUnableToReach "Não foi possível se comunicar com (this user name)"
PleaseTryAgainALittle "Por favor, tente novamente mais tarde."

About the suggestion of multimedia mailbox, in order not to overburden your system, there could be a possibility for offline messages to go to some personal cloud (OneDrive, Google Drive, WebDav and etc). When are you going to translate and update the Android app?

**Comment by brunoalbertopeixoto** [comment]
> Some context...
> 
> ![Screenshot-1](https://user-images.githubusercontent.com/205967/223478798-52776d2b-1cb5-403d-b6dd-81cf18e21cd8.png) ![Screenshot-2](https://user-images.githubusercontent.com/205967/223478854-90bb4a58-2996-402c-b123-ca73f29caced.png) ![Screenshot-3](https://user-images.githubusercontent.com/205967/223478905-ae1300d4-f7d9-49e5-8d74-dee93fc3d6b8.png)
> 
> In the 2nd image "this user" will be a name. The text "is currently not available" needs to be translated ('isCurrentlyNot'). Let me know if you have any questions.
> 
> A multimedia mailbox would be a very nice feature, no doubt. It would also blow up the storage requirements (currently close to zero).

tryToFind "Tentando encontrar (this user name)"
thisCanTakeSomeTime "Isto pode levar algum tempo. Aguarde, por favor..."
isCurrentlyNot "(this user name) não está disponível no momento."
canYouWaitSomeTime "Pode esperar algum tempo enquanto tentamos estabelecer uma ligação?" (I found this text too long.  "Você deseja esperar enquanto tentamos estabelecer uma conexão?
yesPleaseTry "Sim, por favor tente" (I found this text too long.  I would put, even in English, "Sim"/Yes)
noIHaveToGo I found this text too long.  I would put, even in English, "Não"/No)"
TryingToGet "Tentado ligar para (this user name)"
onThePhonePleaseWait "Por favor, aguarde..."
desculpeUnableToReach "Não foi possível se comunicar com (this user name)"
PleaseTryAgainALittle "Por favor, tente novamente mais tarde."

About the suggestion of multimedia mailbox, in order not to overburden your system, there could be a possibility for offline messages to go to some personal cloud (OneDrive, Google Drive, WebDav and etc). When are you going to translate and update the Android app?

**Comment by mehrvarz** [comment]
This is a test account: https://timur.mobi/user/ 12895017440 
It won't pick up, but it will let you see the strings inside the app. (Need to remove the blank in front of the ID.) I'm not sure about plain Yes No. Let me know what you think after looking at it inside the app. Thanks!

**Comment by brunoalbertopeixoto** [comment]
> 

I would just put "yes" and "no". Sentences after yes or no do not add any information.

![Screenshot_2023-03-07-15-22-56](https://user-images.githubusercontent.com/41241891/223516191-ff78ac26-f43c-4e74-ad55-f00c0a59f2dd.png)

![Screenshot_2023-03-07-15-21-57](https://user-images.githubusercontent.com/41241891/223516406-6413259c-7f5e-4763-ba45-3d7a982bc6d7.png)

![Screenshot_2023-03-07-15-21-49](https://user-images.githubusercontent.com/41241891/223516486-70987ac2-f578-4100-b18a-a91e5e16f3b7.png)

**Comment by mehrvarz** [comment]
> I would just put "yes" and "no". Sentences after yes or no do not add any information.

I will consider this. My thought was that the word "No" alone may be too short to be easily tapped. It will require a frame. Then you have two buttons, that need to be sized and positioned, to not look odd. But you may be right anyway.
