### ISSUE TITLE
voicemail message box offline 

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [mehrvarz/webcall#27]
When not online, there could be some function of receiving voice messages, text and files.  In addition there could be a message box and voicemail

**Comment by mehrvarz** [comment]
Voice mail would be nice indeed. Of course this would take some effort to implement properly. It would also put more load on the server and open up new security questions. Hmm..

Let me quickly respond to your full list of features requests. The truth is that I have my very own todo list also. And time is limited. So please don't be disapointed if I am only able to take care of some of the items.

**Comment by brunoalbertopeixoto** [comment]
It's okay if you can't. I really liked the application, so I bring suggestions. As for privacy: 1. There could be data encryption. 2. The files could be hosted on cloud drives (eg Nextcloud and etc). 3. Put the possibility to accept or not the files and voice mailbox. Also, the WebCall server can be serf-hosted

**Comment by mehrvarz** [comment]
wontfix
