### ISSUE TITLE
record and stream call

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [mehrvarz/webcall#28]
I used Jitsi Meet, but it doesn't allow having a single contact login and Wecall allows you to receive calls without the other person needing to install or create a login.  What I miss about WebCall is the ability to receive calls from dial-up (cell) numbers.  Another Jitsi Meet function is the ability to record and stream to YouTube and accept more than one person on the call.

**Comment by mehrvarz** [comment]
wontfix
