### ISSUE TITLE
Connection via internal network, QR Code and Browser 

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [mehrvarz/webcall#31]
There could be an alternative to create, on Android, a server on an internal network to talk to people who are on the same network, but they don't have the app. Could create a link with the data by creating a qrcode.

**Comment by mehrvarz** [comment]
It is not fully clear to me what you exactly want.

**Comment by brunoalbertopeixoto** [comment]
The idea is that the application works also without using data like the application Meshenger 
https://f-droid.org/packages/d.d.meshenger/. The downside of meshenger is that it requires both users to have a login, password and the application installed.

**Comment by mehrvarz** [comment]
WebRTC apps require a server to open firewall ports when this is needed to establish a connection (when calling from one network or ISP to another).

In an intranet-only situation, when no ports need to be opened, WebCall will establish a direkt intranet-only link between the clients. What's wrong with that?

**Comment by mehrvarz** [comment]
offtopic
