### ISSUE TITLE
Video Telephony issue

### ISSUE THREAD

**Issue by NCHU611A** [mehrvarz/webcall#32]
Hi,
When I use the video function, after clicking the "**monitor**" button, the message "**monitor paused**" will be displayed on my screen, but the other party (the person I am chatting with) will still see my video screen (turning head, moving, etc. ).
Thank you.

**Comment by mehrvarz** [comment]
The monitor button lets you pause playback of your local camera on your local device. This is useful if you are using a mobile device and want to reduce battery consumption (in case you don't need both live feeds side by side the whole time) or maybe you just don't want to look at yourself the whole time. Pausing the local monitor does not stop the local camera stream from being delivered to the other side. What you describe is the desired behavior.

**Comment by NCHU611A** [comment]
Ok! got it!
Thank you!
