### ISSUE TITLE
Incoming call on Android 11 doesn't show notification or wake up the screen.

### ISSUE THREAD

**Issue by Chewie9999** [mehrvarz/webcall#36]
I have been testing webcall today for the first time, between a Fairphone 3 (Android 10), and a Samsung Galaxy A70 (Android 11).
On the Fairphone 3, i get the ringing tone and "Accept" notification, when the Samsung calls it, but when I call the Samsung from the Fairphone, I get the ringing tone on the Samsung, but no notification, so you have to wake the screen up, unlock the phone, switch to webcall app and then "Answer" the call.
I am running the stand-alone executable locally. Both devices are on the same LAN segment.

Please let me know what more information you need.

Thanks!

**Comment by mehrvarz** [comment]
This could be some battery-saving feature, preventing the app from waking the screen. It would be helpful to see the client-side log. Give it a call, have it ring once or twice  (no screen-wake / manual pickup) and hang up on the caller side. Wait 10-20s, then wake the Samsung and do: Device optons -> "Capture logs now". When you open Device optons again you should see "Open log file".

**Comment by Chewie9999** [comment]
I got this in the logs during the phone call:
```
01-24 10:37:42.110  2765 12068 D WebCallWebSock: onMessage incoming call name=Chewie ID=11789912000 txtMsg=Test
01-24 10:37:42.110  2765 12068 D WebCallWebSock: onMessage incoming call Android10+ notification
01-24 10:37:42.164  2765 12068 D WebCallService: startRinging
01-24 10:37:48.229  2765  2765 D WebCallService: onTrimMemory level=10
01-24 10:37:50.270  2765 12068 D WebCallWebSock: onMessage cancel got !myWebView or !webviewMainPageLoaded
01-24 10:37:50.270  2765 12068 D WebCallService: stopRinging, from: cancel|
01-24 10:37:50.394  2765 12068 D WebCallWebSock: onMessage sessionId -> calleeIsConnected()
01-24 10:37:50.395  2765 12068 D WebCallService: calleeIsConnected()
01-24 10:37:50.397  2765  2765 D WebCallActivity: broadcastReceiver wsCon state=connected
01-24 10:37:56.272  2765  2765 D WebCallService: onTrimMemory level=10
01-24 10:37:59.746  2765  2765 D WebCallService: onTrimMemory level=5
01-24 10:38:00.732  2765  2765 D WebCallService: onTrimMemory level=5
01-24 10:38:02.317  2765  2765 D WebCallService: onTrimMemory level=5
01-24 10:38:02.903  2765  2765 I ViewRootImpl@10c3aec[WebCallCalleeActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)4 dur=13 res=0x1 s={false 0} ch=false fn=-1
01-24 10:38:02.903  2765  2765 I ViewRootImpl@10c3aec[WebCallCalleeActivity]: stopped(false) old=true
01-24 10:38:02.904  2765  2765 D WebCallActivity: onRestart
01-24 10:38:02.935  2765  2765 D WebCallActivity: onStart
```
[webcall-log-2023-01-24-10-38.txt](https://github.com/mehrvarz/webcall/files/10488758/webcall-log-2023-01-24-10-38.txt)

Attached is the full log file if that helps.
I can't see anything obvious :(

**Comment by mehrvarz** [comment]
A "calleeIsConnected" event with a slightly preceding (almost simultaneous) "cancel" event (aka hangup) is not really good.

10:37:42: startRinging
10:37:50: cancel + calleeIsConnected

The "onTrimMemory" entries indicate memory pressure. Try to free up some memory. You should be able to fetch a log without any onTrimMemory entries in there. Does that still give you a "cancel" event together with the "calleeIsConnected" event?
