### ISSUE TITLE
On Call screen, what does the Audio combo box do?

### ISSUE THREAD

**Issue by Chewie9999** [mehrvarz/webcall#37]
On both Android 10 and 11, when you go to make a call, there is a drop down offering the options of "Audio 1", "Audio 2" and "Audio 3".
What are these?
Different bitrates, devices, or something else?
Thanks!

**Comment by mehrvarz** [comment]
These should be audio output channels. Loudspeaker, speaker phone, ext headset, ...

**Comment by mehrvarz** [comment]
If the browser provides device names, WebCall will show these in the selector, instead of "Audio 1", "Audio 2"...  (Screenshot Chromium on Ubuntu)

![Screenshot-Audio-Selector-Chromium](https://user-images.githubusercontent.com/205967/218485877-77fc9572-7dcd-41f3-83fa-f1a9c630a3a2.png)

**Comment by Chewie9999** [comment]
Thank you for the update. sorry, I should have said - this is using the app itself on Android, not a browser.

**Comment by mehrvarz** [comment]
> Thank you for the update. sorry, I should have said - this is using the app itself on Android, not a browser.

WebCall for Android is running on "a browser". It should be up to the Android WebView component to provide audio device names to the app running on top. A new WebView release might support this at some point.
