### ISSUE TITLE
Docker image for webcall server?

### ISSUE THREAD

**Issue by tonyhkg852** [mehrvarz/webcall#4]
Hello. I really appreciate your work. Considering to self-host the server. Is there any plan to offer docker image as alternative? Thanks!

**Comment by mehrvarz** [comment]
Thank you. I am not using docker and I am therefor not qualified to create such an image. Shall we work on this together?

**Comment by tna76874** [comment]
I would also be interesed in an Docker image. I do not know go - but I have experience with Docker. I did some first steps - but I cannot handle the final error message: `standard_init_linux.go:228: exec user process caused: exec format error`

Steps:
1. Install docker
2. Create `Dockerfile` in repo with content
```
# builder
FROM golang:1.16 AS builder
RUN mkdir /app
WORKDIR /app
ADD . .


RUN bash -c "./gobuild"

# runner
FROM alpine:3.10
WORKDIR /app

COPY --from=builder /app/ /app

EXPOSE 8067

ENTRYPOINT ["/app/init.sh"]
```
3. Build image: `docker build -t webcall .`
4. Run Docker image: `docker run webcall:latest`

**Comment by mehrvarz** [comment]
Go executables are standalone and self-contained. Once you have a working WebCall executable, there should be no Go-specific issues.

> standard_init_linux.go:228: exec user process caused: exec format error

This is a Docker message. I found two posts about it: [1](https://stackoverflow.com/questions/69966425/error-standard-init-linux-go211-exec-user-process-caused-exec-format-error-w) [2](https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025/4)

**Comment by tna76874** [comment]
Thanks - now I'm at the point, that I reach the register page `http://127.0.0.1:8067/callee/register/` but there is no reaction on clicking OK. I added a Dockerfile and a docker-compose.yml

https://github.com/tna76874/webcall/tree/docker

Simply build and start with: `docker-compose up`
Force building: `docker-compose build --no-cache`

**Comment by mehrvarz** [comment]
Use the browser client and look for err messages in the JS console.
EXPOSE 8067 is probably not sufficient. You also need to let wsPort (8071) through. And at some point, depending on your config, also httpsPort and wssPort. How will you make the SSL certificate files accessible to the server? As of now they are expected to exist in the current directory. Will you put these files (including config.ini) inside the Docker file?

**Comment by tna76874** [comment]
I exposed both ports and mapped them to the host. I think about let nginx handle the ssl termination.

**Comment by mehrvarz** [comment]
WebCall server supports (optional) external http(s) proxying, but not for websocket connections. External websocket proxies interfere with always-on connected websocket clients. For a secure setup, the WebCall server needs access to the certificate files. Where is your config.ini file now, inside or outside?

**Comment by tna76874** [comment]
right now there is no persistend config.ini
The docker image starts with the entrypoint `./webcall` - If the file gets created it is inside the container. But making this persistend is no probelm - I'm not familiar with the structure of the code.

**Comment by mehrvarz** [comment]
File structure:
Read-only components: webcall executable + webroot folder (html + js).
You need an external folder for config.ini, db folder, 2 certificate files and (optionally) a backupdb.sh. WebCall generates a stats.ini file in the current directory whenever you stop the server.
