### ISSUE TITLE
Cannot load embed: malformed module path "embed": missing dot in first path element when compiling v3.5.5

### ISSUE THREAD

**Issue by Chewie9999** [mehrvarz/webcall#40]
I am trying to compile webcall 3.5.5 on Ubuntu 20.04.6 LTS, and get the following output:

root@uc1:~/webcall-3.5.5# go build
go: downloading golang.org/x/net v0.7.0
go: downloading github.com/mattn/go-mastodon v0.0.6
go: downloading github.com/nxadm/tail v1.4.8
go: extracting github.com/nxadm/tail v1.4.8
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/mehrvarz/turn/v2 v2.0.12
go: extracting github.com/mattn/go-mastodon v0.0.6
go: extracting go.etcd.io/bbolt v1.3.6
go: downloading github.com/tomnomnom/linkheader v0.0.0-20180905144013-02ca5825eb80
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting github.com/tomnomnom/linkheader v0.0.0-20180905144013-02ca5825eb80
go: downloading gopkg.in/ini.v1 v1.63.0
go: extracting gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/lesismal/nbio v1.2.6
go: extracting gopkg.in/ini.v1 v1.63.0
go: extracting github.com/mehrvarz/turn/v2 v2.0.12
go: downloading github.com/lesismal/llib v1.1.4
go: extracting golang.org/x/net v0.7.0
go: downloading github.com/pion/logging v0.2.2
go: extracting github.com/pion/logging v0.2.2
go: downloading github.com/gorilla/websocket v1.5.0
go: extracting github.com/lesismal/nbio v1.2.6
go: extracting github.com/gorilla/websocket v1.5.0
go: downloading golang.org/x/crypto v0.0.0-20220314234659-1baeb1ce4c0b
go: extracting github.com/lesismal/llib v1.1.4
go: downloading github.com/pion/transport v0.12.3
go: extracting github.com/pion/transport v0.12.3
go: extracting golang.org/x/crypto v0.0.0-20220314234659-1baeb1ce4c0b
go: downloading golang.org/x/sys v0.5.0
go: downloading github.com/pion/stun v0.3.5
go: extracting github.com/pion/stun v0.3.5
go: extracting golang.org/x/sys v0.5.0
go: downloading github.com/pion/randutil v0.1.0
go: extracting github.com/pion/randutil v0.1.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: extracting github.com/fsnotify/fsnotify v1.4.9
go: finding github.com/lesismal/llib v1.1.4
go: finding github.com/lesismal/nbio v1.2.6
go: finding github.com/mattn/go-mastodon v0.0.6
go: finding github.com/mehrvarz/turn/v2 v2.0.12
go: finding github.com/nxadm/tail v1.4.8
go: finding github.com/pion/logging v0.2.2
go: finding go.etcd.io/bbolt v1.3.6
go: finding golang.org/x/crypto v0.0.0-20220314234659-1baeb1ce4c0b
go: finding golang.org/x/net v0.7.0
go: finding gopkg.in/ini.v1 v1.63.0
go: finding github.com/tomnomnom/linkheader v0.0.0-20180905144013-02ca5825eb80
go: finding github.com/gorilla/websocket v1.5.0
go: finding golang.org/x/sys v0.5.0
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding github.com/fsnotify/fsnotify v1.4.9
go: finding github.com/pion/randutil v0.1.0
go: finding github.com/pion/stun v0.3.5
go: finding github.com/pion/transport v0.12.3
build github.com/mehrvarz/webcall: cannot load embed: malformed module path "embed": missing dot in first path element

go version reports "go version go1.13.8 linux/amd64"if that makes any difference.
Thanks!

**Comment by mehrvarz** [comment]
[github.com/mehrvarz/webcall](https://github.com/mehrvarz/webcall#building):
> With Go 1.19 run: go build

[timur.mobi/webcall/install](https://timur.mobi/webcall/install/):
> To build WebCall Server you need Go 1.19 or newer.
>
> Check your Go compiler:
> $ go version
> This should print something like:
> go version go1.19 linux/amd64
