### ISSUE TITLE
gobuild error

### ISSUE THREAD

**Issue by horsepower** [mehrvarz/webcall#6]
gobuild ends with error.
[root@mail webcall]# go version
go version go1.18.1 linux/amd64
[root@mail webcall]# ./gobuild
builddate 2022-04-18
go: downloading github.com/lesismal/llib v1.1.4
go: downloading github.com/lesismal/nbio v1.2.6
go: downloading github.com/mehrvarz/turn/v2 v2.0.12
go: downloading github.com/mrjones/oauth v0.0.0-20190623134757-126b35219450
go: downloading github.com/pion/logging v0.2.2
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading gopkg.in/ini.v1 v1.63.0
go: downloading golang.org/x/crypto v0.0.0-20210513122933-cd7d49e622d5
go: downloading github.com/pion/randutil v0.1.0
go: downloading github.com/pion/stun v0.3.5
go: downloading github.com/pion/transport v0.12.3
go: downloading golang.org/x/sys v0.0.0-20210423082822-04245dca01da
`# github.com/mehrvarz/webcall`
./httpLogin.go:153:6: lenGlobalHubMap declared but not used

**Comment by mehrvarz** [comment]
For the current release, please use Go 1.17 or 1.16 [as suggested here.](https://timur.mobi/webcall/install/)
